"""
Patient message prompt version: v1.0.0.
For changes, create a new version.

Drafts a plain-language message to a patient summarizing their lab results.
This is a SEPARATE LLM call from AI annotation/enrichment: separate prompt,
separate output schema, separate validation and provenance. It is grounded in
the validated, structured findings (de-identified allowlist) — NOT by feeding
the enrichment's free text back in as trusted ground truth.

The draft is always clinician-reviewed before any (demo) send, and the model is
instructed never to include identifiers — the patient's name/email are applied
at render time, never generated by the LLM.
"""

from __future__ import annotations

import json
from typing import Any

from langchain_core.prompts import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    SystemMessagePromptTemplate,
)

# Reuse the structured-result formatting helpers from the annotation prompt so
# both AI calls describe results identically.
from app.ai.prompt_versions.ai_annotation_prompt_v1_0_0 import (
    HistoricalObservation,
    ObservationRow,
    RagChunk,
    format_current_results,
    format_historical_results,
    format_panel_codes,
    format_rag_chunks,
)

PROMPT_VERSION = "v1.0.0"


# ---------------------------------------------------------------------------
# Output schema — patient_message.draft_content_json (JSONB)
# ---------------------------------------------------------------------------

PATIENT_MESSAGE_JSON_SCHEMA = {
    "type": "object",
    "required": [
        "greeting",
        "summary",
        "result_notes",
        "next_steps",
        "disclaimer",
    ],
    "additionalProperties": False,
    "properties": {
        "greeting": {
            "type": "string",
            "description": (
                "A warm, generic salutation with NO name and NO identifier, "
                "e.g. 'Hello,'. The recipient's name is added later by the "
                "system — never invent one."
            ),
        },
        "summary": {
            "type": "string",
            "description": (
                "Two to four plain-language sentences a non-clinician can "
                "understand, summarizing the overall result set: what was "
                "tested, and the general picture (mostly normal, a few items to "
                "keep an eye on, etc.). Avoid jargon; explain any term you use. "
                "Do NOT diagnose or recommend treatment."
            ),
        },
        "result_notes": {
            "type": "array",
            "description": (
                "Optional plain-language notes, one per result worth mentioning "
                "(typically out-of-range or trending values). May be empty if "
                "everything is unremarkable."
            ),
            "items": {
                "type": "object",
                "required": ["analyte_code", "plain_language"],
                "additionalProperties": False,
                "properties": {
                    "analyte_code": {
                        "type": "string",
                        "description": (
                            "Analyte code exactly as provided in the results "
                            "table."
                        ),
                    },
                    "plain_language": {
                        "type": "string",
                        "description": (
                            "One or two sentences explaining this result in "
                            "everyday language: what it measures and what the "
                            "value means relative to the normal range. No "
                            "diagnosis or treatment advice."
                        ),
                    },
                },
            },
        },
        "next_steps": {
            "type": "string",
            "description": (
                "Reassuring, non-alarming guidance framed around clinician "
                "follow-up, e.g. 'Your care team has reviewed these results and "
                "will contact you if anything needs attention.' No specific "
                "medical instructions."
            ),
        },
        "disclaimer": {
            "type": "string",
            "description": (
                "A short disclaimer stating this summary was generated to aid "
                "understanding, has been reviewed by a clinician, and is not a "
                "diagnosis or a substitute for professional medical advice."
            ),
        },
    },
}

OUTPUT_SCHEMA_STR = json.dumps(PATIENT_MESSAGE_JSON_SCHEMA, indent=2)


SYSTEM_TEMPLATE = """\
You are a careful medical communicator drafting a plain-language message to a \
patient about their laboratory results, within an automated pipeline. A \
licensed clinician will review and approve your draft before it is ever sent.

## Constraints
- Write for a layperson at roughly an 8th-grade reading level. Explain any \
medical term you must use.
- Be warm, calm, and reassuring without minimizing genuinely notable findings.
- You are NOT the patient's clinician and your draft is NOT medical advice.
- Do NOT diagnose, and do NOT recommend specific treatments, medications, or doses.
- Ground every statement in the structured results, reference ranges, and \
guideline excerpts provided. Do NOT invent values or reference ranges.
- Do NOT include any patient-identifiable information (name, DOB, MRN, email). \
The greeting must be generic — the system adds the name later.
- Frame follow-up around the patient's care team reviewing the results.

## Output Contract
You MUST respond with a single, raw JSON object that validates against the \
following JSON Schema. Do NOT wrap it in markdown fences or add any preamble.

{output_schema}
"""

SYSTEM_PROMPT = SystemMessagePromptTemplate.from_template(
    SYSTEM_TEMPLATE,
    partial_variables={"output_schema": OUTPUT_SCHEMA_STR},
)


LAB_CONTEXT_TEMPLATE = """\
## Lab Results  (Ingestion ID: {ingestion_id})
Panels: {panel_codes}
Collected: {collected_at}

{current_results_table}
<!-- Format: analyte_code | value | unit | reference_low | reference_high | flag (NORMAL/LOW/HIGH/CRITICAL_LOW/CRITICAL_HIGH) | date -->

---

## Prior Results  (same analytes, last {history_window_days} days)
{historical_results}
<!-- Use only to describe trends in plain language. Absence means first result. -->

---

## Retrieved Clinical Guidelines  (RAG context — {rag_chunk_count} chunk(s))
{rag_chunks}
<!-- Supporting reference material; not ground truth for this patient. -->

---

## Task
Draft ONE plain-language patient message JSON object summarizing the results \
above. Rules:
1. Keep it short, warm, and easy to understand.
2. Add a `result_notes` entry only for results worth mentioning (out of range or \
   notably trending). Skip normal, unremarkable results.
3. Do not invent reference ranges or values — use only what is provided.
4. Do not reference the patient by name or any identifier.
5. Always frame next steps around clinician follow-up.

Respond with the raw JSON object only.
"""

PATIENT_MESSAGE_HUMAN_PROMPT = HumanMessagePromptTemplate.from_template(
    LAB_CONTEXT_TEMPLATE
)


PATIENT_MESSAGE_PROMPT = ChatPromptTemplate.from_messages(
    [SYSTEM_PROMPT, PATIENT_MESSAGE_HUMAN_PROMPT]
)


def build_patient_message_prompt_inputs(
    *,
    ingestion_id: str,
    panel_codes: list[str],
    collected_at: str,
    observations: list[ObservationRow],
    historical_observations: list[HistoricalObservation],
    rag_chunks: list[RagChunk],
    history_window_days: int = 90,
) -> dict[str, Any]:
    """Produce kwargs for PATIENT_MESSAGE_PROMPT.format_messages(**kwargs)."""
    return {
        "ingestion_id": ingestion_id,
        "panel_codes": format_panel_codes(panel_codes),
        "collected_at": collected_at,
        "current_results_table": format_current_results(observations),
        "history_window_days": history_window_days,
        "historical_results": format_historical_results(
            historical_observations
        ),
        "rag_chunk_count": len(rag_chunks),
        "rag_chunks": format_rag_chunks(rag_chunks),
    }
