"""
Patient message prompt version: v1.1.0.
For changes, create a new version.

Drafts a plain-language clinical LETTER to a patient summarizing their lab
results. This is a SEPARATE LLM call from AI annotation/enrichment: separate
prompt, separate output schema, separate validation and provenance. It is
grounded in the validated, structured findings (de-identified allowlist) — NOT
by feeding the enrichment's free text back in as trusted ground truth.

The draft is always clinician-reviewed before any (demo) send. The model is
instructed never to include identifiers, a clinic name, or a clinician
signature — the patient's name, the clinic name and the signature are applied at
render time, never generated by the LLM.
"""

from __future__ import annotations

import json
from typing import Any

from langchain_core.prompts import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    SystemMessagePromptTemplate,
)
from pydantic import BaseModel, Field

# Reuse the structured-result formatting helpers from the annotation prompt so
# both AI calls describe historical results and RAG chunks identically. Current
# results use a message-specific formatter (below) that adds the analyte's
# human-readable name, so the model can write friendly finding titles.
from app.ai.prompt_versions.ai_annotation_prompt_v1_0_0 import (
    HistoricalObservation,
    RagChunk,
    format_historical_results,
    format_panel_codes,
    format_rag_chunks,
)

PROMPT_VERSION = "v1.1.0"


# ---------------------------------------------------------------------------
# Current-results table with human-readable analyte names (message-specific).
# ---------------------------------------------------------------------------


class NamedObservationRow(BaseModel):
    """A single analyte result including its human-readable display name."""

    analyte_code: str
    display: str | None
    value: float | str
    unit: str | None
    reference_low: float | None = Field(default=None)
    reference_high: float | None = Field(default=None)
    flag: str  # NORMAL | LOW | HIGH | CRITICAL_LOW | CRITICAL_HIGH
    date: str  # effective_at


def format_named_results(observations: list[NamedObservationRow]) -> str:
    """Serialise results into a pipe-delimited table that includes the
    analyte's display name so the model can name findings in plain language."""
    header = (
        "analyte_code | name | value | unit | reference_low | "
        "reference_high | flag | date"
    )
    separator = "-" * len(header)
    rows = [header, separator]
    for obs in observations:
        name = obs.display or obs.analyte_code
        low = (
            str(obs.reference_low) if obs.reference_low is not None else "N/A"
        )
        high = (
            str(obs.reference_high)
            if obs.reference_high is not None
            else "N/A"
        )
        rows.append(
            f"{obs.analyte_code} | {name} | {obs.value} | {obs.unit} | "
            f"{low} | {high} | {obs.flag} | {obs.date}"
        )
    return "\n".join(rows)


# ---------------------------------------------------------------------------
# Output schema — patient_message.draft_content_json (JSONB)
# ---------------------------------------------------------------------------

PATIENT_MESSAGE_JSON_SCHEMA = {
    "type": "object",
    "required": [
        "subject",
        "opening",
        "normal_summary",
        "abnormal_findings",
        "recommendation",
    ],
    "additionalProperties": False,
    "properties": {
        "subject": {
            "type": "string",
            "description": (
                "A short subject line describing the TOPIC only, e.g. 'Blood "
                "test results'. Do NOT include a date or the patient's name — "
                "the system adds the date and name later."
            ),
        },
        "opening": {
            "type": "string",
            "description": (
                "One or two sentences telling the patient their results are "
                "available and that this is a summary of the key findings. No "
                "identifiers."
            ),
        },
        "normal_summary": {
            "type": "string",
            "description": (
                "One plain-language sentence rolling up the results that were "
                "within normal ranges, naming the main ones (e.g. 'Most results "
                "were within normal ranges, including blood sugar, potassium, "
                "and several liver and kidney markers.'). Use an empty string if "
                "no results were normal."
            ),
        },
        "abnormal_findings": {
            "type": "array",
            "description": (
                "One entry per out-of-range or notably trending result that "
                "warrants follow-up. Empty array if everything is in range. "
                "Closely related analytes may be grouped into one entry (e.g. "
                "ALT and AST as 'Liver enzymes')."
            ),
            "items": {
                "type": "object",
                "required": ["title", "analyte_codes", "explanation"],
                "additionalProperties": False,
                "properties": {
                    "title": {
                        "type": "string",
                        "description": (
                            "Friendly heading naming the result in lay terms, "
                            "e.g. 'Kidney filtering marker (creatinine)'."
                        ),
                    },
                    "analyte_codes": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": (
                            "Analyte code(s) this finding covers, exactly as "
                            "given in the results table."
                        ),
                    },
                    "explanation": {
                        "type": "string",
                        "description": (
                            "A short plain-language paragraph: what the analyte "
                            "measures, how it deviated from the normal range, any "
                            "trend versus prior results. Do NOT end with a generic "
                            "follow-up/monitoring sentence (e.g. 'your care team "
                            "will follow up on this') — that guidance belongs only "
                            "in `recommendation`, stated once for the whole letter."
                        ),
                    },
                },
            },
        },
        "recommendation": {
            "type": "string",
            "description": (
                "Next-steps guidance framed around clinician follow-up. If there "
                "are abnormal findings, recommend scheduling a follow-up "
                "appointment to discuss them; otherwise reassure that no action "
                "is needed now and the care team will reach out if anything "
                "changes. Do NOT name a clinic or clinician — the system adds the "
                "contact line and signature."
            ),
        },
    },
}

OUTPUT_SCHEMA_STR = json.dumps(PATIENT_MESSAGE_JSON_SCHEMA, indent=2)


SYSTEM_TEMPLATE = """\
You are a careful medical communicator drafting a plain-language LETTER to a \
patient about their laboratory results, within an automated pipeline. A licensed \
clinician will review and approve your draft before it is ever sent.

## Voice and format
- Write a warm, professional letter a layperson can read at roughly an \
8th-grade reading level. Explain any medical term you must use.
- Be calm and reassuring without minimizing genuinely notable findings.
- Roll ALL in-range results into a single plain-language sentence \
(`normal_summary`) — do not list them one by one.
- For results OUTSIDE the normal range, add one `abnormal_findings` entry each \
(closely related analytes such as ALT and AST may be grouped). For each, explain \
what the analyte measures, how it deviated, and any trend versus prior results — \
do NOT add a follow-up/monitoring sentence to each finding; that would repeat \
across findings. State follow-up guidance ONCE, in `recommendation`.

## Constraints
- You are NOT the patient's clinician and your draft is NOT medical advice.
- Do NOT diagnose, and do NOT recommend specific treatments, medications, or doses.
- Ground every statement in the structured results, reference ranges, and \
guideline excerpts provided. Do NOT invent values, reference ranges, or trends.
- Do NOT include any patient-identifiable information (name, DOB, MRN, email), \
and do NOT write a greeting, a date, a clinic name, or a signature — the system \
adds the subject date, the salutation, the contact line, and the signature.

## Output Contract
You MUST respond with a single, raw JSON object that validates against the \
following JSON Schema. Do NOT wrap it in markdown fences or add any preamble.

{output_schema}
"""

SYSTEM_PROMPT = SystemMessagePromptTemplate.from_template(
    SYSTEM_TEMPLATE,
    partial_variables={"output_schema": OUTPUT_SCHEMA_STR},
)


LAB_CONTEXT_TEMPLATE = """\
## Lab Results  (Ingestion ID: {ingestion_id})
Panels: {panel_codes}
Collected: {collected_at}

{current_results_table}
<!-- Format: analyte_code | name | value | unit | reference_low | reference_high | flag (NORMAL/LOW/HIGH/CRITICAL_LOW/CRITICAL_HIGH) | date -->

---

## Prior Results  (same analytes, last {history_window_days} days)
{historical_results}
<!-- Use only to describe trends in plain language. Absence means first result. -->

---

## Retrieved Clinical Guidelines  (RAG context — {rag_chunk_count} chunk(s))
{rag_chunks}
<!-- Supporting reference material; not ground truth for this patient. -->

---

## Task
Draft ONE patient-message JSON object (a letter body) summarizing the results \
above. Rules:
1. Put every in-range result into `normal_summary` (one sentence). Use the flag \
   column to decide what is normal.
2. Add one `abnormal_findings` entry per out-of-range (or notably trending) \
   result; use the analyte's `name` for a friendly title.
3. Do not invent reference ranges, values, or trends — use only what is provided.
4. Do not reference the patient by name or any identifier, and do not add a \
   greeting, date, clinic name, or signature.
5. Frame `recommendation` around clinician follow-up.

Respond with the raw JSON object only.
"""

PATIENT_MESSAGE_HUMAN_PROMPT = HumanMessagePromptTemplate.from_template(
    LAB_CONTEXT_TEMPLATE
)


PATIENT_MESSAGE_PROMPT = ChatPromptTemplate.from_messages(
    [SYSTEM_PROMPT, PATIENT_MESSAGE_HUMAN_PROMPT]
)


def build_patient_message_prompt_inputs(
    *,
    ingestion_id: str,
    panel_codes: list[str],
    collected_at: str,
    observations: list[NamedObservationRow],
    historical_observations: list[HistoricalObservation],
    rag_chunks: list[RagChunk],
    history_window_days: int = 90,
) -> dict[str, Any]:
    """Produce kwargs for PATIENT_MESSAGE_PROMPT.format_messages(**kwargs)."""
    return {
        "ingestion_id": ingestion_id,
        "panel_codes": format_panel_codes(panel_codes),
        "collected_at": collected_at,
        "current_results_table": format_named_results(observations),
        "history_window_days": history_window_days,
        "historical_results": format_historical_results(
            historical_observations
        ),
        "rag_chunk_count": len(rag_chunks),
        "rag_chunks": format_rag_chunks(rag_chunks),
    }
