"""add vector_store table

Revision ID: 02d6b835c69b
Revises: 7d59453e10b2
Create Date: 2026-06-09 12:28:32.053469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '02d6b835c69b'
down_revision: Union[str, Sequence[str], None] = '7d59453e10b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('vector_store',
    sa.Column('embedding_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', Vector(dim=1536), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.Enum('IDENTITY', 'CLINICAL_CONTEXT', 'REF_RANGES', 'INTERPRETATION', 'CONFOUNDERS', name='chunk_type_enum'), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding_model', sa.Text(), nullable=False),
    sa.Column('pipeline_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('embedding_id'),
    sa.UniqueConstraint('source_id', 'chunk_index', 'embedding_model', 'pipeline_version', name='uq_vector_chunk_model_pipeline')
    )
    op.create_index(op.f('ix_vector_store_content_hash'), 'vector_store', ['content_hash'], unique=False)
    op.create_index('ix_vector_store_embedding_hnsw', 'vector_store', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vector_store_embedding_hnsw', table_name='vector_store', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_vector_store_content_hash'), table_name='vector_store')
    op.drop_table('vector_store')
    # ### end Alembic commands ###
