"""Add Panel and Test tables and update Ingestion CHECK constraint

Revision ID: 1288878d4878
Revises: 1369664a9b6b
Create Date: 2026-01-29 14:53:30.663511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1288878d4878'
down_revision: Union[str, Sequence[str], None] = '1369664a9b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panel',
    sa.Column('panel_id', sa.Uuid(), nullable=False),
    sa.Column('ingestion_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Text(), nullable=False),
    sa.Column('panel_code', sa.Text(), nullable=False),
    sa.Column('sample_id', sa.Text(), nullable=True),
    sa.Column('collection_timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_id'], ['ingestion.ingestion_id'], ),
    sa.PrimaryKeyConstraint('panel_id'),
    sa.UniqueConstraint('ingestion_id', 'panel_code', 'sample_id', name='unique_ingestion_panel_sample')
    )
    op.create_table('test',
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('panel_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('test_code', sa.Text(), nullable=False),
    sa.Column('test_name', sa.Text(), nullable=True),
    sa.Column('analyte_type', sa.Text(), nullable=True),
    sa.Column('result_raw', sa.Text(), nullable=False),
    sa.Column('units_raw', sa.Text(), nullable=True),
    sa.Column('result_value_num', sa.Numeric(), nullable=True),
    sa.Column('result_comparator', sa.Text(), nullable=True),
    sa.Column('ref_low_raw', sa.Text(), nullable=True),
    sa.Column('ref_high_raw', sa.Text(), nullable=True),
    sa.Column('flag', sa.Text(), nullable=True),
    sa.CheckConstraint("result_comparator IS NULL OR result_comparator IN ('<', '<=', '>', '>=', '=')", name='check_test_result_comparator'),
    sa.ForeignKeyConstraint(['panel_id'], ['panel.panel_id'], ),
    sa.PrimaryKeyConstraint('test_id'),
    sa.UniqueConstraint('panel_id', 'test_code', 'analyte_type', name='unique_panel_test_analyte')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.drop_table('panel')
    # ### end Alembic commands ###
