"""Initial core models

Revision ID: 1369664a9b6b
Revises: 
Create Date: 2026-01-26 16:48:03.898060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1369664a9b6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion',
    sa.Column('ingestion_id', sa.Uuid(), nullable=False),
    sa.Column('instrument_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('uploader_id', sa.Text(), nullable=False),
    sa.Column('spec_version', sa.Text(), nullable=False),
    sa.Column('uploader_received_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('api_received_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('submitted_sha256', sa.Text(), nullable=True),
    sa.Column('server_sha256', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_filename', sa.Text(), nullable=False),
    sa.Column('ingestion_idempotency_disposition', sa.Text(), nullable=True),
    sa.CheckConstraint("(ingestion_idempotency_disposition IS NULL OR ingestion_idempotency_disposition IN ('CREATED', 'DUPLICATE_IDENTICAL', 'CONFLICT'))", name='ck_ingestion_idempotency_disposition'),
    sa.PrimaryKeyConstraint('ingestion_id'),
    sa.UniqueConstraint('instrument_id', 'run_id', name='unique_instrument_run')
    )
    op.create_table('raw_data',
    sa.Column('ingestion_id', sa.Uuid(), nullable=False),
    sa.Column('content_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('content_mime', sa.Text(), nullable=False),
    sa.Column('content_size_bytes', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_id'], ['ingestion.ingestion_id'], ),
    sa.PrimaryKeyConstraint('ingestion_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_data')
    op.drop_table('ingestion')
    # ### end Alembic commands ###
