"""initial migration

Revision ID: 3025291152a0
Revises: 1288878d4878
Create Date: 2026-02-06 11:23:42.391342

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3025291152a0"
down_revision: Union[str, Sequence[str], None] = "1288878d4878"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diagnostic_report",
        sa.Column("diagnostic_report_id", sa.Uuid(), nullable=False),
        sa.Column("ingestion_id", sa.Uuid(), nullable=False),
        sa.Column("panel_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Text(), nullable=False),
        sa.Column("panel_code", sa.Text(), nullable=False),
        sa.Column("effective_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "normalized_at", sa.TIMESTAMP(timezone=True), nullable=False
        ),
        sa.Column(
            "resource_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "status IN ('FINAL')", name="check_diagnostic_report_status"
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_id"],
            ["ingestion.ingestion_id"],
        ),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["panel.panel_id"],
        ),
        sa.PrimaryKeyConstraint("diagnostic_report_id"),
        sa.UniqueConstraint("panel_id"),
    )
    op.create_index(
        op.f("ix_diagnostic_report_patient_id"),
        "diagnostic_report",
        ["patient_id"],
        unique=False,
    )
    op.create_table(
        "observation",
        sa.Column("observation_id", sa.Uuid(), nullable=False),
        sa.Column("test_id", sa.Uuid(), nullable=False),
        sa.Column("diagnostic_report_id", sa.Uuid(), nullable=False),
        sa.Column("ingestion_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("display", sa.Text(), nullable=True),
        sa.Column("effective_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "normalized_at", sa.TIMESTAMP(timezone=True), nullable=False
        ),
        sa.Column("value_num", sa.Numeric(), nullable=True),
        sa.Column("value_text", sa.Text(), nullable=True),
        sa.Column("comparator", sa.Text(), nullable=True),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("ref_low_num", sa.Numeric(), nullable=True),
        sa.Column("ref_high_num", sa.Numeric(), nullable=True),
        sa.Column("flag", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "resource_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.CheckConstraint(
            "comparator IS NULL OR comparator IN ('<', '<=', '>', '>=', '=')",
            name="check_observation_comparator",
        ),
        sa.CheckConstraint(
            "status IN ('FINAL')", name="check_observation_status"
        ),
        sa.ForeignKeyConstraint(
            ["diagnostic_report_id"],
            ["diagnostic_report.diagnostic_report_id"],
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_id"],
            ["ingestion.ingestion_id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["test.test_id"],
        ),
        sa.PrimaryKeyConstraint("observation_id"),
        sa.UniqueConstraint(
            "diagnostic_report_id",
            "code",
            name="unique_diagnostic_report_id_code",
        ),
        sa.UniqueConstraint("test_id"),
    )
    op.create_index(
        op.f("ix_observation_code"), "observation", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_observation_diagnostic_report_id"),
        "observation",
        ["diagnostic_report_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observation_patient_id"),
        "observation",
        ["patient_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_observation_patient_id"), table_name="observation")
    op.drop_index(
        op.f("ix_observation_diagnostic_report_id"), table_name="observation"
    )
    op.drop_index(op.f("ix_observation_code"), table_name="observation")
    op.drop_table("observation")
    op.drop_index(
        op.f("ix_diagnostic_report_patient_id"), table_name="diagnostic_report"
    )
    op.drop_table("diagnostic_report")
    # ### end Alembic commands ###
