"""initial migration

Revision ID: 36b935e2e407
Revises: 3025291152a0
Create Date: 2026-02-12 11:53:07.377342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36b935e2e407'
down_revision: Union[str, Sequence[str], None] = '3025291152a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_event',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('ingestion_id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=True),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('actor_version', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), server_default=sa.text("'INFO'"), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("\n            (\n              (target_type = 'ingestion' AND target_id IS NULL)\n              OR\n              (target_type <> 'ingestion' AND target_id IS NOT NULL)\n            )\n            ", name='ck_processing_event_target_consistency'),
    sa.CheckConstraint("actor IN ('ingestion-api', 'parser', 'validator', 'normalizer', 'ai-worker')", name='check_processing_event_actor'),
    sa.CheckConstraint("event_type IN ('INGESTION_ACCEPTED', 'INGESTION_DEDUPED_IDENTICAL', 'INGESTION_CONFLICT', 'PARSE_STARTED', 'PARSE_SUCCEEDED', 'PARSE_FAILED', 'VALIDATION_STARTED', 'VALIDATION_SUCCEEDED', 'VALIDATION_FAILED', 'NORMALIZATION_STARTED', 'NORMALIZATION_PHASE1_SUCCEEDED', 'NORMALIZATION_PHASE1_FAILED', 'FHIR_JSON_GENERATION_SUCCEEDED', 'FHIR_JSON_GENERATION_FAILED', 'FHIR_JSON_RESOURCE_FAILED', 'NORMALIZATION_SUCCEEDED', 'NORMALIZATION_FAILED', 'AI_ENRICHMENT_STARTED', 'AI_ENRICHMENT_SKIPPED', 'AI_ENRICHMENT_SUCCEEDED', 'AI_ENRICHMENT_FAILED')", name='check_processing_event_event_type'),
    sa.CheckConstraint("severity IN ('INFO', 'WARN', 'ERROR')", name='check_processing_event_severity'),
    sa.CheckConstraint("target_type IN ('ingestion', 'panel', 'test', 'diagnostic_report', 'observation', 'ai_annotation')", name='check_processing_event_target_type'),
    sa.ForeignKeyConstraint(['ingestion_id'], ['ingestion.ingestion_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_processing_event_ingestion_event_type', 'processing_event', ['ingestion_id', 'event_type'], unique=False)
    op.create_index('ix_processing_event_ingestion_occurred_at', 'processing_event', ['ingestion_id', 'occurred_at'], unique=False)
    op.create_index('ix_processing_event_target_type_id', 'processing_event', ['target_type', 'target_id'], unique=False)
    op.create_index('ux_processing_event_dedupe', 'processing_event', ['ingestion_id', 'event_type', 'dedupe_key'], unique=True, postgresql_where=sa.text('dedupe_key IS NOT NULL'))
    op.add_column('observation', sa.Column('flag_analyzer_interpretation', sa.Text(), nullable=True))
    op.add_column('observation', sa.Column('flag_system_interpretation', sa.Text(), nullable=True))
    op.add_column('observation', sa.Column('discrepancy', sa.Text(), nullable=True))
    op.drop_column('observation', 'flag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observation', sa.Column('flag', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('observation', 'discrepancy')
    op.drop_column('observation', 'flag_system_interpretation')
    op.drop_column('observation', 'flag_analyzer_interpretation')
    op.drop_index('ux_processing_event_dedupe', table_name='processing_event', postgresql_where=sa.text('dedupe_key IS NOT NULL'))
    op.drop_index('ix_processing_event_target_type_id', table_name='processing_event')
    op.drop_index('ix_processing_event_ingestion_occurred_at', table_name='processing_event')
    op.drop_index('ix_processing_event_ingestion_event_type', table_name='processing_event')
    op.drop_table('processing_event')
    # ### end Alembic commands ###
