"""initial migration

Revision ID: 401774e81784
Revises: 36b935e2e407
Create Date: 2026-02-12 21:44:20.338357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '401774e81784'
down_revision: Union[str, Sequence[str], None] = '36b935e2e407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_event',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('ingestion_id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=True),
    sa.Column('target_type', sa.Enum('ingestion', 'panel', 'test', 'diagnostic_report', 'observation', 'ai_annotation', name='processing_event_target_type_enum'), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('INGESTION_ACCEPTED', 'INGESTION_DEDUPED_IDENTICAL', 'INGESTION_CONFLICT', 'PARSE_STARTED', 'PARSE_SUCCEEDED', 'PARSE_FAILED', 'VALIDATION_STARTED', 'VALIDATION_SUCCEEDED', 'VALIDATION_FAILED', 'NORMALIZATION_STARTED', 'NORMALIZATION_RELATIONAL_SUCCEEDED', 'NORMALIZATION_RELATIONAL_FAILED', 'FHIR_JSON_GENERATION_SUCCEEDED', 'FHIR_JSON_GENERATION_FAILED', 'FHIR_JSON_RESOURCE_FAILED', 'NORMALIZATION_SUCCEEDED', 'NORMALIZATION_FAILED', 'AI_ENRICHMENT_STARTED', 'AI_ENRICHMENT_SKIPPED', 'AI_ENRICHMENT_SUCCEEDED', 'AI_ENRICHMENT_FAILED', name='processing_event_type_enum'), nullable=False),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.Enum('ingestion-api', 'parser', 'validator', 'normalizer', 'ai-worker', name='processing_event_actor_enum'), nullable=False),
    sa.Column('actor_version', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARN', 'ERROR', name='processing_event_severity_enum'), server_default=sa.text("'INFO'::processing_event_severity_enum"), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("\n            (\n              (target_type = 'ingestion'::processing_event_target_type_enum AND target_id IS NULL)\n              OR\n              (target_type <> 'ingestion'::processing_event_target_type_enum AND target_id IS NOT NULL)\n            )\n            ", name='ck_processing_event_target_consistency'),
    sa.ForeignKeyConstraint(['ingestion_id'], ['ingestion.ingestion_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_processing_event_ingestion_event_type', 'processing_event', ['ingestion_id', 'event_type'], unique=False)
    op.create_index('ix_processing_event_ingestion_occurred_at', 'processing_event', ['ingestion_id', 'occurred_at'], unique=False)
    op.create_index('ix_processing_event_target_type_id', 'processing_event', ['target_type', 'target_id'], unique=False)
    op.create_index('ux_processing_event_dedupe', 'processing_event', ['ingestion_id', 'event_type', 'dedupe_key'], unique=True, postgresql_where=sa.text('dedupe_key IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_processing_event_dedupe', table_name='processing_event', postgresql_where=sa.text('dedupe_key IS NOT NULL'))
    op.drop_index('ix_processing_event_target_type_id', table_name='processing_event')
    op.drop_index('ix_processing_event_ingestion_occurred_at', table_name='processing_event')
    op.drop_index('ix_processing_event_ingestion_event_type', table_name='processing_event')
    op.drop_table('processing_event')
    # ### end Alembic commands ###
