"""add document table

Revision ID: 7d59453e10b2
Revises: 0f433d750213
Create Date: 2026-06-05 16:33:11.197221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d59453e10b2'
down_revision: Union[str, Sequence[str], None] = '0f433d750213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('doc_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Enum('PANEL', 'ANALYTE', name='document_target_type_enum'), nullable=False),
    sa.Column('target_code', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_format', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('doc_id'),
    sa.UniqueConstraint('content_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    # ### end Alembic commands ###
