"""migrate ai_annotation

Revision ID: f7ee3fee1314
Revises: 02d6b835c69b
Create Date: 2026-06-15 11:55:10.738541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7ee3fee1314'
down_revision: Union[str, Sequence[str], None] = '02d6b835c69b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_annotation',
    sa.Column('ai_annotation_id', sa.Uuid(), nullable=False),
    sa.Column('ingestion_id', sa.Uuid(), nullable=False),
    sa.Column('annotation_type', sa.Enum('ANOMALY_FLAG', 'POSSIBLE_INTERFERENCE', 'FOLLOWUP_SUGGESTION', name='ai_annotation_type_enum'), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model_id', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Text(), nullable=True),
    sa.Column('content_schema_version', sa.Text(), nullable=False),
    sa.Column('input_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('validation_status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='ai_annotation_validation_status_enum'), nullable=True),
    sa.Column('validated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_id'], ['ingestion.ingestion_id'], ),
    sa.PrimaryKeyConstraint('ai_annotation_id')
    )
    op.create_index('ix_ai_annotation_annotation_type', 'ai_annotation', ['annotation_type'], unique=False)
    op.create_index('ix_ai_annotation_validation_status', 'ai_annotation', ['validation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_annotation_validation_status', table_name='ai_annotation')
    op.drop_index('ix_ai_annotation_annotation_type', table_name='ai_annotation')
    op.drop_table('ai_annotation')
    # ### end Alembic commands ###
